---
title: "Cytokinin and Auxin In Apical Dominance"
author: "Alex Lee and Katie Jensen"
date: "April 24, 2017"
output: html_document
---

##Introduction

1.) In plants, apical dominance occurs when auxin (a hormone that acidifies cell walls by causing cells to pump hydrogen atoms into the cell wall) travels rootward down the stalk, inhibiting axillary branching from occurring.  This is an indirect influence via secondary messengers. Auxin downregulates cytokinin (CK) and upregulates strigolactone (SL), hormones that increase and inhibit bud growth, respectively.  When a plant is decapitated, the auxin source is removed and bud growth and expression of Isopentenyl transferase (IPT) -  an enzyme involved in prenylation of adenines as cytokinins - are more likely to increase.  A more in-depth hypothesis of the relationship between and among these hormones, enzymes, and the involved gene groups of interest is shown in Figure 1.

Researchers have previously studied the interactions between auxin and cytokinin hormone signalling pathways in the *Arabidopsis thaliana* plant.  However,  analyses have found very few genes to be differentially expressed in relation to these interactions during the process of apical dominance. The purpose of this study is to conduct revised analyses with the intention of obtaining more information about which genes play a role in auxin-cytokinin interactions and how this affects the process of apical dominance.

2.) Specifically, we would like to know if there are more genes that are differentially expressed than previously found.  If more genes are found, we will analyze their function, interpret the data, and discuss the implications of our findings. 
  
We are also interested in finding alternate explanations for results of research conducted by others and will explore the role of SL in the auxin-cytokinin interaction.

3.) We believe that we will find more genes implicated in these pathways than previously thought, particularly those that may have been overlooked but that could explain the lack of bud initiation in several of the IPT mutants.  
  
#####Hypothesis 1:  

We will find more genes implicated in apical-dominance pathways related to auxin and cytokinin.
  
 Additionally, we expect to find that CK is not regulated directly by auxin. 
  
#####Hypothesis 2:
  
  Auxin only acts directly on SL,  whereas IPTs (IPT3 in particular) mediate the relationship between auxin-SL and CK.

4.) The data we will be using is from the *Arabidopsis thaliana* plant and obtained from NCBI GEO: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE59741.  The basis for our exploratory analyses is a research paper, *Cytokinin is required for escape but not release from auxin mediated apical dominance* (Muller et al, 2015).  Although a hypothesis was not clearly stated, the researchers tested several different variables and relationships:  

a.)	IPT expression levels (of IPT1, IPT3, IPT5, IPT7) were tested (reference gene UBC21) following decapitation to see which are responsive to decapitation. 
 An 8-fold increase in IPT3 was found but there were no significant changes in the other three.

b.)	Effect of mutated (non-functioning) IPT on branching was tested.
Single IPT mutants formed less than one branch on average compared to wildtype(WT); Triple IPT (IPT3,5,7) mutants formed similarly less than one branch; Quadruple IPT mutants (IPT1,3,5,7) formed no branches. The authors stated that these findings are consistent with the role of CK in promoting branching.

c.)	Grafting was done in the triple IPT mutants to test where in the plant IPT is required to promote branching.
Triple IPT mutants significantly reduced branching compared to WT.  A grafted wildtype shoot or root onto the mutant resulted in WT levels of branching.  Therefore, CKs produced in the whole plant rather than the shoot alone contribute to branching in intact plants.

d.)	Muller et al. tested whether the target IPT genes (1, 3, 5, & 7) are required for auxin-mediated apical dominance.  This experiment was conducted by decapitating quadruple, triple, and single IPT mutant plants.
Singl IPT mutants responded to decapitation by producing more branches.  However, triple and quadruple mutants did not.
Of special note, the triple and quadruple mutants initiated very few buds, therefore could not activate buds.  IPT3 showed more empty axils (lack of initiated buds) than wild-type.  Researchers believed that reduced branching in these mutant types is most likely due to the observed lack of bud development. IPT5 and IPT7 had apporixmately the same number of empty axils as wildtype.    

e.)	They also explored the role of SL in CK mutants (arr3,4,5,6,7,15) and compared SL and auxin application to the mutants with wild-type as well as CK mutants that had received only auxin.
SL applied with auxin inhibited buds more than auxin alone did.  Determined a consistency with the canalization-based hypothesis.

f.)	The last variable the researchers looked at was nitrate level. CK mutants were compared to wild-type in high nitrate and low nitrate conditions and found that CK may be important to enhance branching under high nitrate.

Muller et al.(2015) concluded that, "CKs play little part in auxin-mediated  repression and release from apical dominance, but rather they provide a mechanism for buds to escape apical dominance and activate even in the presence of auxin.".



####Conclusion



####Limitations



####Discussion

####Works Cited
        
Müller, D., Waldie, T., Miyawaki, K., To, J. P., Melnyk, C. W., Kieber, J. J., Kakimoto, T., ...     Leyser, O. (January 01, 2015). Cytokinin is required for escape but not release from auxin         mediated apical dominance. The Plant Journal : for Cell and Molecular Biology, 82, 5, 874-86
  